services:
  realtokens-performance-api:
    build: .
    container_name: realtokens-performance-api

    env_file:
      - .env

    volumes:
      - realtokens-performance-logs:/app/logs
      - rent-files-parquet:/app/data/rent_files_parquet

    ports:
      - "${API_PORT_INTERNAL}:${API_PORT_INTERNAL}"

    restart: unless-stopped
    networks:
      - yam-graph

volumes:
  realtokens-performance-logs:
  rent-files-parquet:

networks:
  yam-graph:
    external: true