[supervisord]
user=root
nodaemon=true

[program:api]
command=gunicorn --bind 0.0.0.0:%(ENV_API_PORT_INTERNAL)s --workers 1 --threads 1 "api.app:create_app()"
autostart=true
autorestart=unexpected
startsecs=5
startretries=3
restartsecs=20
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0


[program:scheduler]
command=python3 -m job.scheduler
autostart=true
autorestart=unexpected
startsecs=5
startretries=3
restartsecs=25
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0